// Generated by tools/export_names.py from mkw/names.py - do not edit.
//
// The race logs store ids. These are the only place an id becomes a word, and
// the recorder and the dashboard have to agree about that, so this file is
// generated from the Python tables rather than kept alongside them.

export const CHARACTERS: Record<number, string> = {
  0: "Mario",
  1: "Baby Peach",
  2: "Waluigi",
  3: "Bowser",
  4: "Baby Daisy",
  5: "Dry Bones",
  6: "Baby Mario",
  7: "Luigi",
  8: "Toad",
  9: "Donkey Kong",
  10: "Yoshi",
  11: "Wario",
  12: "Baby Luigi",
  13: "Toadette",
  14: "Koopa Troopa",
  15: "Daisy",
  16: "Peach",
  17: "Birdo",
  18: "Diddy Kong",
  19: "King Boo",
  20: "Bowser Jr.",
  21: "Dry Bowser",
  22: "Funky Kong",
  23: "Rosalina",
};

export const VEHICLES: Record<number, string> = {
  0: "Standard Kart S",
  1: "Standard Kart M",
  2: "Standard Kart L",
  3: "Baby Booster",
  4: "Classic Dragster",
  5: "Offroader",
  6: "Mini Beast",
  7: "Wild Wing",
  8: "Flame Flyer",
  9: "Cheep Charger",
  10: "Super Blooper",
  11: "Piranha Prowler",
  12: "Tiny Titan",
  13: "Daytripper",
  14: "Jetsetter",
  15: "Blue Falcon",
  16: "Sprinter",
  17: "Honeycoupe",
  18: "Standard Bike S",
  19: "Standard Bike M",
  20: "Standard Bike L",
  21: "Bullet Bike",
  22: "Mach Bike",
  23: "Flame Runner",
  24: "Bit Bike",
  25: "Sugarscoot",
  26: "Wario Bike",
  27: "Quacker",
  28: "Zip Zip",
  29: "Shooting Star",
  30: "Magikruiser",
  31: "Sneakster",
  32: "Spear",
  33: "Jet Bubble",
  34: "Dolphin Dasher",
  35: "Phantom",
};

export const COURSES: Record<number, string> = {
  0: "Mario Circuit",
  1: "Moo Moo Meadows",
  2: "Mushroom Gorge",
  3: "Grumble Volcano",
  4: "Toad's Factory",
  5: "Coconut Mall",
  6: "DK Summit",
  7: "Wario's Gold Mine",
  8: "Luigi Circuit",
  9: "Daisy Circuit",
  10: "Moonview Highway",
  11: "Maple Treeway",
  12: "Bowser's Castle",
  13: "Rainbow Road",
  14: "Dry Dry Ruins",
  15: "Koopa Cape",
  16: "GCN Peach Beach",
  17: "GCN Mario Circuit",
  18: "GCN Waluigi Stadium",
  19: "GCN DK Mountain",
  20: "DS Yoshi Falls",
  21: "DS Desert Hills",
  22: "DS Peach Gardens",
  23: "DS Delfino Square",
  24: "SNES Mario Circuit 3",
  25: "SNES Ghost Valley 2",
  26: "N64 Mario Raceway",
  27: "N64 Sherbet Land",
  28: "N64 Bowser's Castle",
  29: "N64 DK's Jungle Parkway",
  30: "GBA Bowser Castle 3",
  31: "GBA Shy Guy Beach",
};

export const ITEMS: Record<number, string> = {
  0: "Green Shell",
  1: "Red Shell",
  2: "Banana",
  3: "Fake Item Box",
  4: "Mushroom",
  5: "Triple Mushrooms",
  6: "Bob-omb",
  7: "Blue Shell",
  8: "Lightning",
  9: "Star",
  10: "Golden Mushroom",
  11: "Mega Mushroom",
  12: "Blooper",
  13: "POW Block",
  14: "Thunder Cloud",
  15: "Bullet Bill",
  16: "Triple Green Shells",
  17: "Triple Red Shells",
  18: "Triple Bananas",
  19: "(unused)",
  20: "-",
};

export const OBJECT_TYPES: Record<number, string> = {
  0: "Green Shell",
  1: "Red Shell",
  2: "Banana",
  4: "Star",
  5: "Blue Shell",
  7: "Fake Item Box",
  9: "Bob-omb",
  12: "Golden Mushroom",
};

export const VS_POINTS: Record<number, number> = {
  1: 15,
  2: 12,
  3: 10,
  4: 8,
  5: 7,
  6: 6,
  7: 5,
  8: 4,
  9: 3,
  10: 2,
  11: 1,
  12: 0,
};

export const DAMAGE_TYPES: Record<number, [string, string]> = {
  0: ["Spin-out", "Banana"],
  1: ["Spin-out", "an enemy"],
  2: ["Knockback", "Shell or Fake Item Box"],
  3: ["Knockback", "a boosted kart, cow or car"],
  4: ["Knockback", "Chain Chomp"],
  5: ["Knockback", "a Moonview car"],
  6: ["Knockback", "Bullet Bill"],
  7: ["Launched", "Bob-omb or Blue Shell"],
  8: ["Launched", "a Cataquack"],
  9: ["Fiery spin-out", "fire"],
  10: ["Spin-out", "Lightning"],
  11: ["POW'd", "POW Block"],
  12: ["Crushed", "a Thwomp"],
  13: ["Crushed", "Mega Mushroom"],
  14: ["Crushed", "a Moonview truck"],
  15: ["Spin-out", "a Zapper"],
  16: ["Crushed", "a Thwomp, then respawned"],
  17: ["Spin-out", "Thunder Cloud"],
};

// Damage types that can only have come from an item somebody used.
export const BY_ITEM = new Set([0, 2, 7, 10, 11, 13, 17]);

// The gap between the per-racer clock (starts at the intro) and the
// race clock (starts at GO): whoever is on pole is otherwise credited
// the countdown as time spent leading.
export const COUNTDOWN_FRAMES = 412;

// Progress samples per second, and the step size that means a racer
// crossed the line rather than moved.
export const TRACK_HZ = 5;
export const JUMP = 0.5;

export const courseName = (code: number | null | undefined): string =>
  code == null
    ? "(course unknown)"
    : COURSES[code] ?? `course 0x${code.toString(16).padStart(2, "0")}`;
