#!/usr/bin/env python3
"""Write mkw/names.py out as TypeScript, so the dashboard uses the same tables.

    python3 -m tools.export_names

The recorder stores ids, never names, so the tables in `mkw/names.py` are the
only place a number becomes a word. The dashboard is TypeScript and needs the
same mapping; copying it by hand would mean a correction to a character id
landing in one of the two files and not the other. This generates the other
one. Re-run it after editing `mkw/names.py`; the file it writes is checked in
so `npm run dev` works without Python.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mkw import addresses as A
from mkw.events import JUMP, TRACK_HZ
from mkw.names import (BY_ITEM, CHARACTERS, COURSES, DAMAGE_TYPES, ITEMS,
                       OBJECT_TYPES, VEHICLES, VS_POINTS)

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "web", "src", "data", "names.ts")

HEAD = """// Generated by tools/export_names.py from mkw/names.py - do not edit.
//
// The race logs store ids. These are the only place an id becomes a word, and
// the recorder and the dashboard have to agree about that, so this file is
// generated from the Python tables rather than kept alongside them.

"""


def table(name, mapping, value=json.dumps, kind="string"):
    lines = ["export const %s: Record<number, %s> = {" % (name, kind)]
    for k in sorted(mapping):
        lines.append("  %d: %s," % (k, value(mapping[k])))
    lines.append("};")
    return "\n".join(lines)


def main():
    parts = [
        HEAD.rstrip("\n"),
        table("CHARACTERS", CHARACTERS),
        table("VEHICLES", VEHICLES),
        table("COURSES", COURSES),
        table("ITEMS", ITEMS),
        table("OBJECT_TYPES", OBJECT_TYPES),
        table("VS_POINTS", VS_POINTS, value=str, kind="number"),
        # [what it did, what can have done it]
        table("DAMAGE_TYPES", DAMAGE_TYPES,
              value=lambda v: json.dumps(list(v)), kind="[string, string]"),
        "// Damage types that can only have come from an item somebody used.\n"
        "export const BY_ITEM = new Set(%s);" % json.dumps(sorted(BY_ITEM)),
        "// The gap between the per-racer clock (starts at the intro) and the\n"
        "// race clock (starts at GO): whoever is on pole is otherwise credited\n"
        "// the countdown as time spent leading.\n"
        "export const COUNTDOWN_FRAMES = %d;" % A.COUNTDOWN_FRAMES,
        "// Progress samples per second, and the step size that means a racer\n"
        "// crossed the line rather than moved.\n"
        "export const TRACK_HZ = %d;\nexport const JUMP = %s;"
        % (TRACK_HZ, JUMP),
        'export const courseName = (code: number | null | undefined): string =>\n'
        '  code == null\n'
        '    ? "(course unknown)"\n'
        '    : COURSES[code] ?? `course 0x${code.toString(16).padStart(2, "0")}`;',
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n\n".join(parts) + "\n")
    print("wrote %s" % os.path.relpath(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
